import { useState } from "react";
import Head from "next/head";

import Center from "../../components/layout/Center";
import Title from "../../components/items/Title";
import Card from "../../components/sets/Card";
import ModalSlide from "../../components/sets/ModalSlide";
import { formacoes } from "../../data/projetos-formacoes";

import { AnimatePresence } from "framer-motion";
import { Swiper, SwiperSlide } from "swiper/react";
import SwiperCore, { Navigation } from "swiper";
import "swiper/css";
import "swiper/css/navigation";

SwiperCore.use([Navigation]);

export default function Formacoes() {

  //Modal
  //Define qual modal deve aparecer
  //Ativa ou desativa o modal
  const [modal, setModalOpen] = useState(0);
  const [open, setOpen] = useState(false);

  return (
    <>
      <Head>
        <title>Creche Chico Xavier</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center>
        <header>
          <Title
            title="Formações"
            subtitle="Há quatro décadas acolhemos crianças e suas famílias, colaborando para a construção de vidas mais felizes."
          />
        </header>
        <Swiper spaceBetween={50} slidesPerView={4.4} navigation={true}>
          {formacoes.map((formacao) => (
            <SwiperSlide key={formacao.key}>
              <Card
                title={formacao.title}
                subtitle={formacao.subtitle}
                imageTop={formacao.link}
                cardOnCLick={() => (
                  <>
                    {setOpen(true)}
                    {setModalOpen(formacao.key)}
                  </>
                )}
              />
            </SwiperSlide>
          ))}
        </Swiper>
        <AnimatePresence initial={false}>
          {open && (
            <ModalSlide
              key={formacoes[modal].key}
              onClick={() => setOpen(false)}
              title={formacoes[modal].title}
              subtitle={formacoes[modal].subtitle}
              images={formacoes[modal].images}
            />
          )}
        </AnimatePresence>
      </Center>
      <style jsx>{`
        main header .title {
          color: #ffc420 !important;
        }

        main nav .card {
          background: #ffc420;
        }

        .card::after {
          background: #fff;
        }

        .images {
          position: relative;
          width: 40rem;
          height: 40rem;
        }
      `}</style>

      <style jsx global>{`
        main .swiper {
          position: relative;
          width: 100vw;
          margin: 0;
          padding: 3rem 5rem 5rem;
        }

        main .swiper-slide {
        }
      `}</style>
    </>
  );
}
