import { useState } from "react";
import Head from "next/head";
import { useKeenSlider } from "keen-slider/react";
import "keen-slider/keen-slider.min.css";
import { AnimatePresence } from "framer-motion";
import Center from "../../components/layout/Center";
import Title from "../../components/items/Title";
import Card from "../../components/sets/Card";
import Modal from "../../components/sets/Modal";
import { formacoes } from "../../data/projetos-formacoes";

export default function Formacoes() {
  //KeenSlider
  //Define o Ref do KeenSlider
  const [sliderRef] = useKeenSlider({ slidesPerView: 4, spacing: 30 });
  //Modal
  //Define qual modal deve aparecer
  //Ativa ou desativa o modal
  const [modal, setModalOpen] = useState(0);
  const [open, setOpen] = useState(false);

  return (
    <>
      <Head>
        <title>Creche Chico Xavier</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center>
        <header>
          <Title
            title="Formações"
            subtitle="Há quatro décadas acolhemos crianças e suas famílias, colaborando para a construção de vidas mais felizes."
          />
        </header>
        <nav ref={sliderRef} className="keen-slider">
          {formacoes.map((formacao) => (
            <Card
              key={formacao.key}
              title={formacao.title}
              subtitle={formacao.subtitle}
              imageTop={formacao.link}
              cardOnCLick={() => (
                <>
                  {setOpen(true)}
                  {setModalOpen(formacao.key)}
                </>
              )}
              className="keen-slider__slide"
            />
          ))}
        </nav>
        <AnimatePresence initial={false}>
          {open && (
            <Modal
              key={formacoes[modal].key}
              onClick={() => setOpen(false)}
              title={formacoes[modal].title}
              subtitle={formacoes[modal].subtitle}
              images={formacoes[modal].images}
            />
          )}
        </AnimatePresence>
      </Center>
      <style sjx>{`
			main header {
				display: flex;
				flex-direction: column;
				align-items: center;
			}
			
			main header .title {
				color: #ffc420 !important;
			}

			main nav {
				width: 100vw;
				overflow-y: hidden;
				overflow-x: auto;
				padding: 4rem 6rem 5rem 2rem;
				margin-bottom: -5rem;
				gap: 0;
			}

			main nav .card {
				background: #ffc420;
			}

			.card::after {
				background: #fff;
			}
			
			.keen-slider {
				justify-content: flex-start;
			}

			.images {
				position: relative;
				width: 40rem;
				height: 40rem;
			}

			`}</style>
    </>
  );
}
