import { useState } from "react";
import Head from "next/head";
import Center from "../../components/layout/Center";
import Title from "../../components/items/Title";
import Card from "../../components/sets/Card";
import { projetos } from "../../data/projetos-links";

export default function Projetos() {
	const [nossaCreche, setNossaCreche] = useState(true);
	const [missao, setMissao] = useState(false);
	const [historia, sethistoria] = useState(false);

	return (
		<>
			<Head>
				<title>Creche Chico Xavier</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Center>
				<Title title="Conheça" span="Nossos projetos" />
				<nav>
					{projetos.map((projeto) => (
						<Card
							key={projeto.link}
							title={projeto.title}
							subtitle={projeto.subtitle}
							imageTop={projeto.link}
							cardOnCLick={projeto.link}
						/>
					))}
				</nav>
			</Center>
			<style jsx global>{``}</style>
		</>
	);
}
