import { useRouter } from "next/router";
import Head from "next/head";
import Center from "../../components/layout/Center";
import Title from "../../components/items/Title";
import Card from "../../components/sets/Card";
import { projetos } from "../../data/projetos-links";
import { motion } from "framer-motion";

export default function Projetos() {
  //Router dos cards para as páginas: Formações / Projetos de Leitura / Juntos somos mais
  const router = useRouter();
  // Animações dos Cards
  const list = {
    animate: { transition: { staggerChildren: 0.05 } },
    exit: { transition: { staggerChildren: 0.05 } },
  };
  const animationMenu = {
    initial: { y: 100, opacity: 0 },
    animate: { y: 0, opacity: 1, transition: { staggerChildren: 1 } },
    exit: { opacity: 0, y: 30, transition: { staggerChildren: 1 } },
  };

  return (
    <>
      <Head>
        <title>Creche Chico Xavier</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Center>
        <Title title="Conheça" span="Nossos projetos" />

        <motion.nav
          initial="initial"
          animate="animate"
          exit="exit"
          variants={list}
        >
          {projetos.map((projeto) => (
            <motion.div key={projeto.link} variants={animationMenu}>
              <Card
                title={projeto.title}
                span={projeto.span}
                imageTop={projeto.link}
                cardOnCLick={() => router.push(projeto.link)}
              />
            </motion.div>
          ))}
        </motion.nav>
      </Center>
      <style jsx global>{``}</style>
    </>
  );
}
