import { useState } from "react";
import Head from "next/head";

import Center from "../../components/layout/Center";
import Title from "../../components/items/Title";
import MenuButton from "../../components/items/MenuButton";
import Card from "../../components/sets/Card";
import ModalSlide from "../../components/sets/ModalSlide";
import { vinteUm } from "../../data/projetos-jsm";

import { AnimatePresence } from "framer-motion";
import { Swiper, SwiperSlide } from "swiper/react";
import SwiperCore, { Navigation } from "swiper";
import "swiper/css";
import "swiper/css/navigation";

SwiperCore.use([Navigation]);

export default function JuntosSomosMais() {
  //Modal
  //Define qual modal deve aparecer
  //Ativa ou desativa o modal
  const [modal, setModalOpen] = useState(0);
  const [open, setOpen] = useState(false);

  const [projeto, setProjeto] = useState(0);

  return (
    <>
      <Head>
        <title>Creche Chico Xavier</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center>
        <header>
          <Title title="Juntos" span="Somos Mais" />
          <div className="jsm-projetos">
            {vinteUm.map((menuItem) => (
              <MenuButton
                key={menuItem.key}
                link={menuItem.link}
                title={menuItem.title}
                image={menuItem.image}
                vert={menuItem.vert}
                span={menuItem.span}
                onCLick={() => setProjeto(menuItem.key)}
              />
            ))}
          </div>
        </header>
        <Swiper spaceBetween={50} slidesPerView={3.8} navigation={true}>
          {vinteUm[projeto].eventos.map((jsm) => (
            <SwiperSlide key={jsm.key} className="sliderCapa">
              <Card
                title={jsm.title}
                span={jsm.span}
                subtitle={jsm.subtitle}
                imageTop={jsm.link}
                objectFit="cover"
                objectPosition="50% 0%"
                cardOnCLick={() => (
                  <>
                    {setOpen(true)}
                    {setModalOpen(jsm.key)}
                  </>
                )}
              />
            </SwiperSlide>
          ))}
        </Swiper>
        <AnimatePresence initial={false}>
          {open && (
            <ModalSlide
              key={vinteUm[projeto].eventos[modal].key}
              onClick={() => setOpen(false)}
              title={vinteUm[projeto].eventos[modal].title}
              span={vinteUm[projeto].eventos[modal].span}
              subtitle={vinteUm[projeto].eventos[modal].subtitle}
              slidesPerView={1.5}
              images={vinteUm[projeto].eventos[modal].images}
            />
          )}
        </AnimatePresence>
      </Center>

      <style jsx>{`
        main nav {
          width: 100vw;
          overflow-y: hidden;
          overflow-x: auto;
          padding: 4rem 2rem 5rem 2rem;
          margin-bottom: -5rem;
          gap: 0;
        }

        main nav .card {
          background: #ffc420;
        }

        .card::after {
          background: #fff;
        }

        .images {
          position: relative;
          width: 40rem;
          height: 40rem;
        }

        .jsm-projetos {
          display: flex;
          gap: 2rem;
        }
      `}</style>

      <style jsx global>{`
        main .swiper {
          position: relative;
          width: 100vw;
          margin: 0;
          padding: 3rem 5rem 5rem;
        }

        .card {
          padding: 2rem;
        }

        .card h1 {
          font-size: 2.3rem !important;
        }

        .card h2 {
          font-size: 2.3rem;
        }

        .card header .cardImage {
          filter: none;
        }

        .modal .modalContent .images {
          position: relative;
          width: 100%;
          height: 50rem;
          margin: 0 auto;
        }

        .modal .modalContent .images img {
          border-radius: 2rem;
        }

        .modal .modalCard .modalContent .swiper-slide {
          background: none !important;
          outline: none !important;
          padding: 0 !important;
        }

        .sliderCapa img {
          border-radius: 2rem;
        }
      `}</style>
    </>
  );
}
