import { useState } from "react";
import Head from "next/head";

import Center from "../../components/layout/Center";
import Title from "../../components/items/Title";
import Card from "../../components/sets/Card";
import ModalDataSlide from "../../components/sets/ModalDataSlide";
import { vinteUm } from "../../data/projetos-leitura";

import { AnimatePresence } from "framer-motion";
import { Swiper, SwiperSlide } from "swiper/react";
import SwiperCore, { Navigation } from "swiper";
import "swiper/css";
import "swiper/css/navigation";

SwiperCore.use([Navigation]);

var data = new Date();
var mes = Number(data.getMonth());
var meses = [
  "janeiro",
  "fevereiro",
  "março",
  "abril",
  "maio",
  "junho",
  "julho",
  "agosto",
  "setembro",
  "outubro",
  "novembro",
  "dezembro"
];

export default function ProjetosDeLeitura() {
  //Modal
  //Define qual modal deve aparecer
  //Ativa ou desativa o modal
  const [modal, setModalOpen] = useState(0);
  const [open, setOpen] = useState(false);

  return (
    <>
      <Head>
        <title>Creche Chico Xavier</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center>
        <header>
          <Title
            title="Projetos de Leitura"
            subtitle="Há quatro décadas acolhemos crianças e suas famílias, colaborando para a construção de vidas mais felizes."
          />
        </header>
        <Swiper spaceBetween={50} slidesPerView={4.4} navigation={true}>
          {vinteUm.map((projeto) => (
            <SwiperSlide key={projeto.key}>
              <Card
                title={projeto.title}
                span={projeto.span}
                subtitle={projeto.subtitle}
                imageTop={projeto.link}
                cardOnCLick={() => (
                  <>
                    {setOpen(true)}
                    {setModalOpen(projeto.key)}
                  </>
                )}
              />
            </SwiperSlide>
          ))}
        </Swiper>
        <AnimatePresence initial={false}>
          {open && (
            <ModalDataSlide
              onClick={() => setOpen(false)}
              title={vinteUm[modal].title}
              subtitle={vinteUm[modal].subtitle}
              images={vinteUm[modal]}
              dados={meses}
              inicial={mes}
            />
          )}
        </AnimatePresence>
      </Center>

      <style jsx>{`
        main header .title {
          color: #ffc420 !important;
        }

        main .card {
          background: #ffc420;
        }

        .card::after {
          background: #fff;
        }

        .images {
          position: relative;
          width: 40rem;
          height: 40rem;
        }
      `}</style>

      <style jsx global>{`
        main .swiper {
          position: relative;
          width: 100vw;
          margin: 0;
          padding: 3rem 5rem 5rem;
        }

        main .swiper-slide {
        }
      `}</style>
    </>
  );
}
