import Head from "next/head";
import Link from "next/link";

export default function Acreche() {
  return (
    <>
      <Head>
        <title>Creche Chico Xavier</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>A Nossa Creche</h1>
        <Link href="/">Creche Link</Link>
        <Link href="/acreche">A Nossa Creche</Link>
      </main>

      <style jsx>{``}</style>
      <style jsx global>{`
        .bg {
          background: radial-gradient(
            84.49% 84.49% at 50% 57.14%,
            #144bb8 0%,
            #550077 100%
          ) !important;
        }

        .hills {
          filter: brightness(0.5) hue-rotate(50deg) !important;
        }
      `}</style>
    </>
  );
}
