import { useState } from "react";
import Head from "next/head";

import Columns from "../components/layout/Columns";
import Title from "../components/items/Title";
import MenuButton from "../components/items/MenuButton";
import Card from "../components/sets/Card";
import { nossoSonho } from "../data/nosso-sonho";
import Modal from "../components/sets/Modal";

import Media from "react-media";

export default function NossoSonho() {
  //Card
  //Define qual modal deve aparecer
  //Ativa ou desativa o modal
  const [cardNumber, setCardNumber] = useState(0);
  const [modalOpen, setModalOpen] = useState(false);

  const [projeto, setModal] = useState(0);

  return (
    <>
      <Head>
        <title>Creche Chico Xavier</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Columns>
        <div className="left">
          <Title
            title="Junte-se ao"
            span="Nosso Sonho"
            subtitle="A Creche Chico Xavier atende 106 crianças e aproximadamente 100 famílias em período integral."
          >
            <nav>
              {nossoSonho.map((menuItem) => (
                <MenuButton
                  key={menuItem.key}
                  link={menuItem.link}
                  title={menuItem.title}
                  span={menuItem.span}
                  image={true}
                  vert={true}
                  onClick={() => (
                    <>
                      {setCardNumber(menuItem.key)}
                      {setModalOpen(true)}
                    </>
                  )}
                />
              ))}
            </nav>
          </Title>
        </div>
        <Media query="(min-width: 875px)">
          {(matches) => {
            return matches ? (
              <div className="right">
                <Card
                  title={
                    nossoSonho[cardNumber].title +
                    " " +
                    nossoSonho[cardNumber].span
                  }
                  icon={nossoSonho[cardNumber].link}
                >
                  {nossoSonho[cardNumber].documentos}
                </Card>
              </div>
            ) : (
              <>
                {" "}
                {modalOpen && (
                  <Modal
                    title={
                      nossoSonho[cardNumber].title +
                      " " +
                      nossoSonho[cardNumber].span
                    }
                    className="modal-title"
                    onClick={() => <>{setModalOpen(false)}</>}
                  >
                    {nossoSonho[cardNumber].documentos}
                  </Modal>
                )}
              </>
            );
          }}
        </Media>
      </Columns>

      <style jsx>{``}</style>

      <style jsx global>{`
        .left .subTitle,
        .right .subtitle {
          max-width: 70rem;
        }

        .cardImage {
          position: fixed;
          width: 22vw;
          height: 32rem;
          margin: 1rem auto 2rem;
          outline: 1rem solid #fff;
          border-radius: 2rem;
          -webkit-transform: rotateZ(1deg);
          -ms-transform: rotateZ(1deg);
          transform: rotateZ(6deg);
          box-shadow: 0.1rem 0.3rem 5rem -0.6rem hsl(356deg 70% 30% / 63%);
          right: 4vw;
        }

        .cardContent div {
          margin-top: 3rem;
          font-size: 2rem;
          line-height: 3.3rem;
        }

        .cardContent .cardInfo h2 {
          font-size: 2.4rem;
          font-weight: bold;
          color: hsl(195deg 80% 40%);
        }

        @media (max-width: 875px) {
          .cardInfo {
            margin: 3rem 0;
            font-size: 2rem;
            line-height: 3rem;
            text-align: center;
          }

          .cardImage {
            display: none;
          }

          .modalCard .modalContent p {
            text-align: center;
          }

        }
      `}</style>
    </>
  );
}
