import { useState } from "react";
import Head from "next/head";

import Columns from "../components/layout/Columns";
import Title from "../components/items/Title";

import Image from "next/image";

export default function NossoSonho() {
  //Card
  //Define qual modal deve aparecer
  //Ativa ou desativa o modal
  const [cardNumber, setCardNumber] = useState(0);
  const [modalOpen, setModalOpen] = useState(false);

  const [projeto, setModal] = useState(0);

  return (
    <>
      <Head>
        <title>Creche Chico Xavier</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Columns>
        <div className="left">
          <Title title="Junte-se ao" span="Nosso Sonho"></Title>
          <h2>SANTANDER</h2>
          <div>
            <b>CONTA:</b> 13.001644-7
            <br />
            <b>AGÊNCIA:</b> 0053
            <br />
            <b>CNPJ:</b> 48.554.190/0001-15
            <br />
            <b>PIX</b>: 12 98137 7272
            <br />
            <h2>CAIXA</h2>
            <b>PIX:</b> 48.554.190/0001-15
            <br />
          </div>
        </div>
        <div className="right">
          <div className="cardImage">
            <Image
              src="/images/nosso sonho/turma.jpg"
              layout="fill"
              objectFit="cover"
            />
          </div>
        </div>
      </Columns>

      <style jsx>{``}</style>

      <style jsx global>{`
        main {
          flex-direction: row-reverse;
        }

        main .left .subTitle,
        main .right .subtitle {
          max-width: 70rem;
        }

        main .left {
          font-size: 3rem;
          line-height: 4.2rem;
          color: #fff;
        }

        main .left h2 {
          font-family: "Lilita One", cursive;
          font-size: 5rem;
          font-weight: normal;
          letter-spacing: 0.1rem;
          color: #fff;
        }

        main .left b {
          letter-spacing: 0.1rem;
          color: hsl(44deg 100% 56%);
        }

        main .right {
          top: 4rem;
          width: -webkit-fill-available;
          height: auto;
        }

        .card {
          width: -webkit-fill-available;
        }

        .cardImage {
          position: relative;
          width: -webkit-fill-available;
          height: auto;
          margin: 0 auto 3rem;
          outline: 1rem solid #fff;
          border-radius: 2rem;
          box-shadow: 0.5rem 1.3rem 3rem -0.6rem hsl(356deg 70% 30% / 63%);
          transform: rotate(2deg);
        }

        .cardImage div {
          border-radius: 2rem;
        }

        @media (max-width: 875px) {
          .right {
            display: none;
          }
        }
      `}</style>
    </>
  );
}
