import Head from "next/head";

export default function Transparencia() {
  return (
    <>
      <Head>
        <title>Creche Chico Xavier</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>SITE</h1>
      </main>
    </>
  );
}