import { useState } from "react";
import Head from "next/head";
import Columns from "../components/layout/Columns";
import Title from "../components/items/Title";
import MenuButtom from "../components/items/MenuButtom";
import CardSlideData from "../components/sets/CardSlideData";
import CardSlide from "../components/sets/CardSlide";
import { transparencia } from "../data/transparencia-dados";

var meses = [
	"janeiro",
	"fevereiro",
	"março",
	"abril",
	"maio",
	"junho",
	"julho",
	"agosto",
	"setembro",
	"outubro",
	"novembro",
	"dezembro",
];

export default function Transparencia() {
	const [docs, setDocs] = useState(0);

<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> parent of 8d7b7bd (Alteração do layout Transparência)
	return (
		<>
			<Head>
				<title>Creche Chico Xavier</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Columns>
				<div className="left">
					<Title
						title="Transparência"
						subtitle="A Casa da Criança Creche Chico Xavier tem também como objetivo, atuar de forma transparente e atender a legislação da Transparência Municipal e atender o Termo de Colaboração Nº001. Desta forma, a instituição vem através desta página, disponibilizar publicamente o acesso as suas prestações de contas.">
<<<<<<< HEAD
						<nav>
							{transparencia.map((menuItem) => (
								<MenuButtom
									key={menuItem.key}
									link={menuItem.link}
									title={menuItem.title}
									span={menuItem.span}
									image={menuItem.image}
									vert={menuItem.vert}
									onCLick={() => setDocs(menuItem.key)}
								/>
							))}
						</nav>
					</Title>
				</div>
				<div className="right">
					{docs === 1 ? (
						<CardSlide
							key={transparencia[docs].key}
							icon={transparencia[docs].link}
							title={transparencia[docs].title}
							subtitle={transparencia[docs].subtitle}
							slides={transparencia[docs].documentos}
							slidesPerView={3.5}
=======
						{transparencia.map((menuItem) => (
							<MenuButtom
								key={menuItem.key}
								link={menuItem.link}
								title={menuItem.title}
								image={menuItem.image}
								vert={menuItem.vert}
								span={menuItem.span}
								onCLick={() => setDocs(menuItem.key)}
							/>
						))}
					</Title>
				</div>
				<div className="right">
					{docs === 0 ? (
						<CardSlide
							key={transparencia[docs].key}
							title={transparencia[docs].title}
							subtitle={transparencia[docs].subtitle}
							slides={transparencia[docs].documentos}
>>>>>>> parent of 8d7b7bd (Alteração do layout Transparência)
							className="CardTransp"
						/>
					) : (
						<CardSlideData
							key={transparencia[docs].key}
							title={transparencia[docs].title}
							subtitle={transparencia[docs].subtitle}
							className="CardTransp"
						/>
					)}
				</div>
			</Columns>
			<style jsx>{``}</style>
<<<<<<< HEAD
=======
  return (
    <>
      <Head>
        <title>Creche Chico Xavier</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Columns>
        <div className="left">
          <Title
            title="Transparência"
            subtitle="A Casa da Criança Creche Chico Xavier tem também como objetivo, atuar de forma transparente e atender a legislação da Transparência Municipal e atender o Termo de Colaboração Nº001. Desta forma, a instituição vem através desta página, disponibilizar publicamente o acesso as suas prestações de contas."
          >
            <nav>
              {transparencia.map((menuItem) => (
                <MenuButtom
                  key={menuItem.key}
                  link={menuItem.link}
                  title={menuItem.title}
                  span={menuItem.span}
                  image={menuItem.image}
                  vert={menuItem.vert}
                  onCLick={() => setDocs(menuItem.key)}
                />
              ))}
            </nav>
          </Title>
        </div>
        <div className="right">
          {docs === 0 ? (
            <CardSlide
              key={transparencia[docs].key}
              icon={transparencia[docs].link}
              title={transparencia[docs].title}
              subtitle={transparencia[docs].subtitle}
              slides={transparencia[docs].documentos}
              slidesPerView={3.5}
              className="CardTransp"
            />
          ) : (
            <CardSlideData
              key={transparencia[docs].key}
              title={transparencia[docs].title}
              subtitle={transparencia[docs].subtitle}
              className="CardTransp"
            />
          )}
        </div>
      </Columns>
      <style jsx>{``}</style>
>>>>>>> parent of 4ca0624 (Testando o Swiper)
=======
>>>>>>> parent of 8d7b7bd (Alteração do layout Transparência)

			<style jsx global>{`
				.left .subTitle,
				.right .subtitle {
					max-width: 70rem;
				}
			`}</style>
		</>
	);
}
